PralnaDemo/Models/City.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PralnaDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Organizations = new HashSet<Organization>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Organization> Organizations { get; set; }
    }
}

PralnaDemo/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PralnaDemo.Models;

namespace PralnaDemo.Controllers
{
    public class CityController : Controller
    {
        private PralnaEntities db = new PralnaEntities();

        // GET: /City/
        public ActionResult Index()
        {
            return View(db.Cities.ToList());
        }

        // GET: /City/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: /City/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /City/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: /City/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: /City/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(city);
        }

        // GET: /City/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: /City/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PralnaDemo/Controllers/DivisionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PralnaDemo.Models;

namespace PralnaDemo.Controllers
{
    public class DivisionController : Controller
    {
        private PralnaEntities db = new PralnaEntities();

        // GET: /Division/
        public ActionResult Index()
        {
            var divisions = db.Divisions.Include(d => d.ParentDivision).Include(d => d.Organization);
            return View(divisions.ToList());
        }

        // GET: /Division/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Division division = db.Divisions.Find(id);
            if (division == null)
            {
                return HttpNotFound();
            }
            return View(division);
        }

        // GET: /Division/Create
        public ActionResult Create()
        {
            ViewBag.ParentDivisionId = new SelectList(db.Divisions, "Id", "Name");
            ViewBag.OrganizationId = new SelectList(db.Organizations, "Id", "Name");
            return View();
        }

        // POST: /Division/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,ParentDivisionId,OrganizationId")] Division division)
        {
            if (ModelState.IsValid)
            {
                db.Divisions.Add(division);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ParentDivisionId = new SelectList(db.Divisions, "Id", "Name", division.ParentDivisionId);
            ViewBag.OrganizationId = new SelectList(db.Organizations, "Id", "Name", division.OrganizationId);
            return View(division);
        }

        // GET: /Division/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Division division = db.Divisions.Find(id);
            if (division == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentDivisionId = new SelectList(db.Divisions, "Id", "Name", division.ParentDivisionId);
            ViewBag.OrganizationId = new SelectList(db.Organizations, "Id", "Name", division.OrganizationId);
            return View(division);
        }

        // POST: /Division/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,ParentDivisionId,OrganizationId")] Division division)
        {
            if (ModelState.IsValid)
            {
                db.Entry(division).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ParentDivisionId = new SelectList(db.Divisions, "Id", "Name", division.ParentDivisionId);
            ViewBag.OrganizationId = new SelectList(db.Organizations, "Id", "Name", division.OrganizationId);
            return View(division);
        }

        // GET: /Division/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Division division = db.Divisions.Find(id);
            if (division == null)
            {
                return HttpNotFound();
            }
            return View(division);
        }

        // POST: /Division/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Division division = db.Divisions.Find(id);
            db.Divisions.Remove(division);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PralnaDemo/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PralnaDemo.Models;

namespace PralnaDemo.Controllers
{
    public class OrganizationController : Controller
    {
        private PralnaEntities db = new PralnaEntities();

        // GET: /Organization/
        public ActionResult Index()
        {
            var organizations = db.Organizations.Include(o => o.City);
            return View(organizations.ToList());
        }

        // GET: /Organization/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

        // GET: /Organization/Create
        public ActionResult Create()
        {
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name");
            return View();
        }

        // POST: /Organization/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,Description,CityId")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Organizations.Add(organization);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", organization.CityId);
            return View(organization);
        }

        // GET: /Organization/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", organization.CityId);
            return View(organization);
        }

        // POST: /Organization/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Description,CityId")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Entry(organization).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", organization.CityId);
            return View(organization);
        }

        // GET: /Organization/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

        // POST: /Organization/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Organization organization = db.Organizations.Find(id);
            db.Organizations.Remove(organization);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PralnaDemo/Controllers/StatisticController.cs
using PralnaDemo.BusinessLogic;
using PralnaDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PralnaDemo.Controllers
{
    public class StatisticController : Controller
    {
        PralnaEntities db = new PralnaEntities();

        //
        // GET: /Statistic/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cities()
        {
            CitiesStatisticOperations someCitiesStatOp = new CitiesStatisticOperations(db);
            return View(someCitiesStatOp.GetCitiesStat());

        }
        

        public ActionResult City(int id)
        {
            CityOperations cityStatOp = new CityOperations(db);
            OrganizationOperations orgOp = new OrganizationOperations(db);
            ViewBag.OrganizationStatistic = orgOp.GetWorstOrganizationGraph(cityStatOp.GetCityStatistic(id).OrganizationStatistic);
            ViewBag.BestOrganizationStatistic = orgOp.GetBestOrganizationGraph(cityStatOp.GetCityStatistic(id).OrganizationStatistic);            
            return View(cityStatOp.GetCityStatistic(id));
        }

        // shows ordered list of divisions 
        public ActionResult Organization(int id)
        {
            OrganizationStatistic someOrgStat = new OrganizationStatistic(db, db.Organizations.Find(id));
            OrganizationOperations orgOp = new OrganizationOperations(db);
            someOrgStat = orgOp.GetOrganizationStatistic(id, false);
            orgOp.FillDivisionsStatistic(someOrgStat, false);
            return View(someOrgStat);
        }

        // shows ordered list of workplaces
        public ActionResult Division(int id)
        {
            DivisionStatistic someDivisionStat = new DivisionStatistic(db, db.Divisions.Find(id));
            DivisionsOperations divOp = new DivisionsOperations(db);
            someDivisionStat = divOp.GetDivisionStatistic(id, false);
            divOp.FillWorkplacesStatistic(someDivisionStat);
            return View(someDivisionStat);
        }

        // shows ordered list of workers
        public ActionResult Workplace(int id)
        {
            WorkplaceStatistic someWorkplaceStat = new WorkplaceStatistic(db, db.WorkPlaces.Find(id));
            WorkplacesOperations workplaceOp = new WorkplacesOperations(db);
            someWorkplaceStat = workplaceOp.GetWorkplacesStatistic(id, false);
            workplaceOp.FillWorkersStatistic(someWorkplaceStat);
            return View(someWorkplaceStat);
        }

        // shows ordered list of workers
        public ActionResult Worker(int id)
        {
            WorkerStatistic someWorkerStat = new WorkerStatistic(db, db.Workers.Find(id));
            WorkerOperations workerOp = new WorkerOperations(db);          
            someWorkerStat = workerOp.FillWorkerStatistic(db.Workers.Find(id));           

            return View(someWorkerStat);
        }

        public PartialViewResult ServicesList(int workerId, int serviceType, int valueType)
        {
            IEnumerable<ServiceToClient> model = db.ServiceToClients.Where(m => m.ValueSet.HasValue).Where(m => m.WorkerId == workerId).Where(m => m.ServiceTypeId == serviceType).Where(m=> m.Value == valueType);
            if(valueType == 1)
            {
                ViewBag.IsSuccess = true;
            }
            else
            {
                ViewBag.IsSuccess = false;
            }

            return PartialView(model);
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
	}
}

PralnaDemo/Views/Statistic/Cities.cshtml
@model PralnaDemo.Models.CitiesStatistic

@{
    ViewBag.Title = "Статистика по містах";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/fusioncharts")

<h2>Статистика по містах</h2>

<script>
    FusionCharts.ready(function ()
    {
        var revenueChart = new FusionCharts({
            "type": "pie3d",
            "renderAt": "chartContainer",
            "width": "500",
            "height": "300",
            "dataFormat": "json",
            "dataSource": {
                "chart": {
                    "caption": "Використання послуг",
                /*    "paletteColors": "#6495ED, #FF7F00", */
                    /*"subCaption": "За весь час",*/
                    "showPercentInTooltip": "1",
                    "useDataPlotColorForLabels": "1",                   
                    "theme": "fint"
                },
                "data": @Html.Raw(Model.GraphData)                   
            }
        });

        revenueChart.render();
    })
</script>
<table>
        <tr class="graphOuter">
            <td><div id="chartContainer"></div></td>
            <td>
                <table class="graphStat">
                    <tr class="text-primary">
                        <td>Місто</td>
                        <td class="text-right">Сервісів</td>
                    </tr>
                    @foreach (PralnaDemo.Models.CityStatistic item in Model.CitiesStats)
                    {
                        <tr>
                            <td><a href="/Statistic/City/@item.City.Id">@item.City.Name</a></td>
                            <td class="text-right">
                                @item.ServicesProvided (@PralnaDemo.Utils.StringOperations.GetPercent(Model.TotalServicesProvided, item.ServicesProvided)%)
                            </td>
                        </tr>
                    }
                    <tr class="totalRow">
                        <td>Разом</td>
                        <td class="text-right">@Model.TotalServicesProvided (100%)</td>
                    </tr>
                </table>
            </td>
        </tr>

</table>

<br />
@Html.Partial("SummaryCitiesStat", Model)

<br />
<script>
    FusionCharts.ready(function ()
    {
        var treemapChart = new FusionCharts({
            "type": "treemap",
            "renderAt": "treeMapContainer",
            "width": "700",
            "height": "500",
            "dataFormat": "json",
            "dataSource": {
                "chart": {
                    "caption": "Загальна мапа по країні",
                    "paletteColors": "#EE0000, #7FFF00",

                    "animation": "0",
                    "hideTitle": "1",					
                    "plotToolText": "<div><b>$label</b><br/> <b>Послуг: </b>$value<br/><b>Рівень незадоволеності: </b>$svalue%</div>",
                    "spacex": "0",
                    "spacey": "0",
                    "horizontalPadding": "1",
                    "verticalPadding": "1",
                    "hoveronallsiblingleaves": "1",
                    "plotborderthickness": ".5",
                    "plotbordercolor": "666666",
                    "legendpadding": "0",
                    "legendItemFontSize": "10",
                    "legendItemFontBold": "1",
                    "showLegend": "1",
                    "legendPointerWidth": "8",
                    "legenditemfontcolor": "3d5c5c",
                    "algorithm": "squarified",
               
                    "legendScaleLineThickness": "0",
                    "legendCaptionFontSize": "10",
                    "subcaption": "Рівень задоволеності по організаціям міст",
                    "legendCaption": "Фильтр по рівню незадоволеності",
                    "theme": "zune"

                  
                },
                "data": @Html.Raw(Model.TreeMapData)
            }
        });

        treemapChart.render();
    })
</script>
<div id="treeMapContainer"></div>


<br />
<script>
	FusionCharts.ready(function ()
	{
		var detailedTreemapChart = new FusionCharts({
			"type": "treemap",
			"renderAt": "detailedTreeMapContainer",
			"width": "700",
			"height": "500",
			"dataFormat": "json",
			"dataSource": {
				"chart": {
					"caption": "Загальна мапа по країні (по робітникам)",
					"paletteColors": "#EE0000, #7FFF00",

					"animation": "0",
					"hideTitle": "1",					
					"plotToolText": "<div><b>$label</b><br/> <b>Послуг: </b>$value<br/><b>Рівень незадоволеності: </b>$svalue%</div>",
					"spacex": "0",
					"spacey": "0",
					"horizontalPadding": "1",
					"verticalPadding": "1",
					"hoveronallsiblingleaves": "1",
					"plotborderthickness": ".5",
					"plotbordercolor": "666666",
					"legendpadding": "0",
					"legendItemFontSize": "10",
					"legendItemFontBold": "1",
					"showLegend": "1",
					"legendPointerWidth": "8",
					"legenditemfontcolor": "3d5c5c",
					"algorithm": "squarified",
               
					"legendScaleLineThickness": "0",
					"legendCaptionFontSize": "10",
					"subcaption": "Рівень задоволеності по організаціям міст",
					"legendCaption": "Фильтр по рівню незадоволеності",
					"theme": "zune"

                  
				},
				"data": @Html.Raw(Model.DetailedTreeMapData)
                }
        });

		detailedTreemapChart.render();
    })
</script>
<div id="detailedTreeMapContainer"></div>


@*
<div>@Html.Raw(Model.TreeMapData.Replace("\r\n", "<br>").Replace("\t", "&nbsp;&nbsp;&nbsp;&nbsp;"))</div>
*@

PralnaDemo/Views/Statistic/Division.cshtml
@model PralnaDemo.Models.DivisionStatistic

@{
    ViewBag.Title = "Дані по відділу";
    Layout = "~/Views/Shared/_Layout.cshtml";
    PralnaDemo.BusinessLogic.DivisionsOperations divisionOp = new PralnaDemo.BusinessLogic.DivisionsOperations(Model.db);
     PralnaDemo.Models.DivisionStatistic someDivisionStat = divisionOp.GetDivisionStatistic(Model.Division.Id, false);
     divisionOp.FillWorkplacesStatistic(someDivisionStat);  
}
@Scripts.Render("~/bundles/fusioncharts")

<h5>
    <a href="/Statistic/Cities/">
        Усі міста
    </a> >
    <a title="По місту в цілому" href="/Statistic/City/@Model.Division.Organization.City.Id">
        @Model.Division.Organization.City.Name
    </a> >
    <a title="По організації в цілому" href="/Statistic/Organization/@Model.Division.OrganizationId">
        @Model.Division.Organization.Name
    </a> >    
        @Model.Division.Name   
</h5>




<script>
    FusionCharts.ready(function ()
    {
        var summaryIndexChart = new FusionCharts({
            type: 'angulargauge',
            renderAt: 'summary-chart-container',
            width: '400',
            height: '250',
            dataFormat: 'json',
            dataSource: {
                "chart": {
                    "caption": "Рівень незадоволеності якістю послуг відділу",
                    "subcaption": "@Model.Division.Name",
                    "showValue": "1",
                    "lowerLimit": "0",
                    "upperLimit": "100",
                    "gaugeFillMix": "{dark-30},{light-60},{dark-10}",
                    "gaugeFillRatio": "15",
                    "theme": "fint"
                },
                "colorRange": {
                    "color": [
                        {
                            "minValue": "0",
                            "maxValue": "50",
                            "code": "#6baa01"
                           
                        },
                        {
                            "minValue": "50",
                            "maxValue": "75",
                            "code": "#f8bd19"
                        },
                        {
                            "minValue": "75",
                            "maxValue": "100",
                            "code": "#e44a00"                            
                        }
                    ]
                },
                "dials": {
                    "dial": [{
                        "value": "@Model.SummaryIndex.ToString("0.##")"
                    }]
                }
            }
        });
        summaryIndexChart.render();
    })
</script>

<br />
<table>
    <tr class="graphOuter">
        <td>
            <div id="summary-chart-container"></div>
        </td>
        <td>
            <table class="graphStat">
                <tr class="text-primary">
                    <td colspan="2">Відгуків</td>
                </tr>
                <tr>
                    <td>Задовільно</td>
                    <td>@Model.SuccessServicesProvided (@PralnaDemo.Utils.StringOperations.GetPercent(Model.ServicesProvided, Model.SuccessServicesProvided)%)</td>
                </tr>
                <tr>
                    <td>Не задовільно</td>
                    <td>@Model.FailedServicesProvided (@PralnaDemo.Utils.StringOperations.GetPercent(Model.ServicesProvided, Model.FailedServicesProvided)%)</td>
                </tr>
                <tr class="totalRow">
                    <td>Разом</td>
                    <td>@Model.ServicesProvided</td>
                </tr>
            </table>

        </td>
    </tr>

</table>
<br />



<script>
    FusionCharts.ready(function ()
    {
        var worstWorkplaces = new FusionCharts({
            "type": "bar3d",
            "renderAt": "worstWorkplacesContainer",
            "width": "500",
            "height": "300",
            "dataFormat": "json",
            "dataSource": {
                "chart": {
                    "caption": "Посади з найбільшою кількостю негативних відгуків",                   
                    "yAxisName": "Негативні відгуки, %",
                    "paletteColors": "#EE0000",
                    "bgColor": "#ffffff",
                    "showBorder": "0",
                    "showCanvasBorder": "0",
                    "usePlotGradientColor": "0",
                    "plotBorderAlpha": "10",
                    "placeValuesInside": "1",
                    "valueFontColor": "#ffffff",
                    "showAxisLines": "1",
                    "axisLineAlpha": "25",
                    "divLineAlpha": "10",
                    "alignCaptionWithCanvas": "0",
                    "showAlternateVGridColor": "0",
                    "captionFontSize": "14",
                    "subcaptionFontSize": "14",
                    "subcaptionFontBold": "0",
                    "toolTipColor": "#ffffff",
                    "toolTipBorderThickness": "0",
                    "toolTipBgColor": "#000000",
                    "toolTipBgAlpha": "80",
                    "toolTipBorderRadius": "2",
                    "toolTipPadding": "5",
                    "theme": "fint"
                },
                "data": @Html.Raw(divisionOp.RenderWorkplacesStatistic(someDivisionStat))
            }
        });

        worstWorkplaces.render();
    })
</script>

<table>
    <tr class="graphOuter">
        <td>
            <div id="worstWorkplacesContainer"></div>
        </td>
        <td>
            <table class="graphStat">
                <tr class="text-primary">
                    <td>Посада</td>
                    <td>Незадоволеність</td>
                    <td>Відгуків позитивних</td>
                    <td>Відгуків негативних</td>                            
                </tr>
                @foreach (PralnaDemo.Models.WorkplaceStatistic item in Model.WorkplaceStatistics.OrderByDescending(m => m.SummaryIndex))
                {
                    <tr>
                        <td><a href="/Statistic/Workplace/@item.WorkPlace.Id">@item.WorkPlace.Name</a> </td>
                        <td>@item.SummaryIndex.ToString("0.##") %</td>
                        <td>@item.SuccessServicesProvided</td>
                        <td>@item.FailedServicesProvided</td>
                    </tr>
                }
            </table>

        </td>
    </tr>
</table>

PralnaDemo/Views/Statistic/Index.cshtml
@{
    ViewBag.Title = "Статистика";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Статистика</h2>

@Html.ActionLink("По містах", "Cities", "Statistic")
<br />
@Html.ActionLink("По місту", "City", "Statistic", new  {id = 1 }, null)
<br />
@Html.ActionLink("По організації", "Organization", "Statistic", new { id = 1 }, null)
<br />
@Html.ActionLink("По відділу", "Division", "Statistic", new { id = 1 }, null)
<br />
@Html.ActionLink("По посаді", "Workplace", "Statistic", new { id = 1 }, null)
<br />
@Html.ActionLink("По робітнику", "Worker", "Statistic", new { id = 1 }, null)
<br />

PralnaDemo/Views/Statistic/ServicesList.cshtml
@model  IEnumerable<PralnaDemo.Models.ServiceToClient>

@if (ViewBag.IsSuccess == false)
{
    <h4>Негативні відгуки</h4>
    <table class="table table-striped table-hover">
        <tr class="text-primary">
            <td>№ квитка</td>
            <td>Дата</td>
            <td>
                Порушення
            </td>
            <td>Коментар</td>
        </tr>

        @foreach (PralnaDemo.Models.ServiceToClient item in Model)
        {
            <tr>
                <td>@item.UniqueKey</td>
                <td>@item.ValueSet</td>
                <td>
                    @foreach (PralnaDemo.Models.FoundViolation violationItem in item.FoundViolations)
                    {
                        <span>@violationItem.ViolationType.Name</span>
                    }
                </td>
                <td>@item.ClientFeedback</td>
            </tr>
        }

    </table>
}
else if (ViewBag.IsSuccess == true)
{
    <h4>Позитивні відгуки</h4>
    <table class="table table-striped table-hover">
        <tr class="text-primary">
            <td>№ квитка</td>
            <td>Дата</td>
           </tr>
            @foreach (PralnaDemo.Models.ServiceToClient item in Model)
            {
                <tr>
                    <td>@item.UniqueKey</td>
                    <td>@item.ValueSet</td>
                </tr>           
            }
        </table>
 }